version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t  microservice:1 .
      - docker tag microservice:1 118781765982.dkr.ecr.us-east-1.amazonaws.com/microservice-118781765982-ecr-repository
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 118781765982.dkr.ecr.us-east-1.amazonaws.com/microservice-118781765982-ecr-repository
